# Configurations
title: GitBook | Choewy
longtitle: GitBook | Choewy
author: 최원영
email: choewy32@gmail.com
github: "https://github.com/choewy"
tistory: "https://choewy.tistory.com"
description: >
  백엔드 개발자의 기술 블로그

version: 1.0
gitbook_version: 3.2.3

url: "https://choewy.github.io"
baseurl: "/gitbook"
rss: RSS

toc:
  enabled: true
  h_min: 1
  h_max: 3

# markdown render engine.
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: github

markdown_ext: markdown,mkdown,mkdn,mkd,md

# /:categories/:year:month:day/:title:output_ext
permalink: /:categories/:title

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

destination: ./_site
incremental: false
regenerate: true

plugins:
  - jekyll-feed
  - jemoji
